
trigger:
  - none

pool: taskify-pool

steps: 
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)\env\dev'
      backendServiceArm: 'taskify2'
      backendAzureRmOverrideSubscriptionID: '11100f00-f288-40b5-934d-b9ded6ba5396'
      backendAzureRmResourceGroupName: 'taskify-rg'
      backendAzureRmStorageAccountName: 'taskifystorage123'
      backendAzureRmContainerName: 'taskifycontainer'
      backendAzureRmKey: 'taskifyshruti'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: 'terraform -version'
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'validate'
      workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'

  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
      environmentServiceNameAzureRM: 'taskify2'
      environmentAzureRmOverrideSubscriptionID: '11100f00-f288-40b5-934d-b9ded6ba5396'